// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.u64().name("job_id"),
  variantId: __t.string().primaryKey().name("variant_id"),
  campaignId: __t.string().name("campaign_id"),
  briefId: __t.string().name("brief_id"),
  parentVariantId: __t.option(__t.string()).name("parent_variant_id"),
  rootVariantId: __t.string().name("root_variant_id"),
  depth: __t.u8(),
  operation: __t.string(),
  instruction: __t.option(__t.string()),
  imagePrompt: __t.string().name("image_prompt"),
  headline: __t.string(),
  cta: __t.string(),
  aspectRatio: __t.string().name("aspect_ratio"),
  model: __t.string(),
  quality: __t.string(),
  status: __t.string(),
  imageUrl: __t.option(__t.string()).name("image_url"),
  xaiFileId: __t.option(__t.string()).name("xai_file_id"),
  costUsdTicks: __t.u64().name("cost_usd_ticks"),
  error: __t.option(__t.string()),
  starred: __t.bool(),
  approved: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
