// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  snapshotId: __t.string().primaryKey().name("snapshot_id"),
  brand: __t.string(),
  brandUserId: __t.string().name("brand_user_id"),
  title: __t.string(),
  sourceRunId: __t.string().name("source_run_id"),
  people: __t.u32(),
  niches: __t.u32(),
  payload: __t.string(),
  createdAt: __t.u64().name("created_at"),
  archivedAt: __t.timestamp().name("archived_at"),
});
