// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  membershipId: __t.string().primaryKey().name("membership_id"),
  brandUserId: __t.string().name("brand_user_id"),
  followerUserId: __t.string().name("follower_user_id"),
  discoveredAt: __t.timestamp().name("discovered_at"),
  ingestionRunId: __t.string().name("ingestion_run_id"),
  source: __t.string(),
});
