// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  brandUserId: __t.string().primaryKey().name("brand_user_id"),
  displayName: __t.string().name("display_name"),
  productDescription: __t.string().name("product_description"),
  valueProps: __t.array(__t.string()).name("value_props"),
  palette: __t.array(__t.string()),
  visualStyle: __t.string().name("visual_style"),
  bannedClaims: __t.array(__t.string()).name("banned_claims"),
  referenceImageUrls: __t.array(__t.string()).name("reference_image_urls"),
  updatedAt: __t.timestamp().name("updated_at"),
});
