// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  brandUserId: __t.string().primaryKey().name("brand_user_id"),
  posts: __t.u32(),
  likes: __t.f64(),
  reposts: __t.f64(),
  replies: __t.f64(),
  quotes: __t.f64(),
  views: __t.f64(),
  likeScale: __t.f64().name("like_scale"),
  repostScale: __t.f64().name("repost_scale"),
  replyScale: __t.f64().name("reply_scale"),
  quoteScale: __t.f64().name("quote_scale"),
  viewScale: __t.f64().name("view_scale"),
  baselineRunId: __t.string().name("baseline_run_id"),
  note: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
