// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  videoId: __t.string().primaryKey().name("video_id"),
  brand: __t.string(),
  campaignId: __t.string().name("campaign_id"),
  news: __t.string(),
  goal: __t.string(),
  status: __t.string(),
  progress: __t.f64(),
  title: __t.string(),
  videoUrl: __t.string().name("video_url"),
  thumbnailUrl: __t.string().name("thumbnail_url"),
  durationS: __t.f64().name("duration_s"),
  scriptJson: __t.string().name("script_json"),
  reviewJson: __t.string().name("review_json"),
  error: __t.option(__t.string()),
  requestedBy: __t.identity().name("requested_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
