// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  linkId: __t.string().primaryKey().name("link_id"),
  campaignId: __t.string().name("campaign_id"),
  draft: __t.string(),
  videoId: __t.string().name("video_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
