// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  campaignId: __t.string().primaryKey().name("campaign_id"),
  brandUserId: __t.string().name("brand_user_id"),
  name: __t.string(),
  goal: __t.string(),
  offer: __t.option(__t.string()),
  channel: __t.string(),
  aspectRatio: __t.string().name("aspect_ratio"),
  segments: __t.array(__t.string()),
  variantsPerBrief: __t.u8().name("variants_per_brief"),
  status: __t.string(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
