// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  campaignId: __t.string().primaryKey().name("campaign_id"),
  brand: __t.string(),
  source: __t.string(),
  stage: __t.string(),
  draftA: __t.string().name("draft_a"),
  draftB: __t.string().name("draft_b"),
  experimentId: __t.u64().name("experiment_id"),
  videoId: __t.string().name("video_id"),
  winnerText: __t.string().name("winner_text"),
  requestedBy: __t.identity().name("requested_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  shippedAt: __t.option(__t.timestamp()).name("shipped_at"),
});
