// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BriefTheme,
} from "./types";


export default __t.row({
  briefId: __t.string().primaryKey().name("brief_id"),
  campaignId: __t.string().name("campaign_id"),
  segment: __t.string(),
  version: __t.u32(),
  audienceLabel: __t.string().name("audience_label"),
  share: __t.f64(),
  twinCount: __t.u32().name("twin_count"),
  get keyInterests() {
    return __t.array(BriefTheme).name("key_interests");
  },
  get avoid() {
    return __t.array(BriefTheme);
  },
  tone: __t.string(),
  messageAngle: __t.string().name("message_angle"),
  valueProps: __t.array(__t.string()).name("value_props"),
  headlineOptions: __t.array(__t.string()).name("headline_options"),
  cta: __t.string(),
  visualCues: __t.array(__t.string()).name("visual_cues"),
  visualAvoid: __t.array(__t.string()).name("visual_avoid"),
  format: __t.string(),
  model: __t.string(),
  evidenceJson: __t.option(__t.string()).name("evidence_json"),
  editedByUser: __t.bool().name("edited_by_user"),
  createdAt: __t.timestamp().name("created_at"),
});
