// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  campaignId: __t.string(),
  brandUserId: __t.string(),
  name: __t.string(),
  goal: __t.string(),
  offer: __t.option(__t.string()),
  channel: __t.string(),
  aspectRatio: __t.string(),
  segments: __t.array(__t.string()),
  variantsPerBrief: __t.u8(),
};
