// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.u64().primaryKey().name("job_id"),
  campaignId: __t.string().name("campaign_id"),
  kind: __t.string(),
  targetId: __t.string().name("target_id"),
  instruction: __t.option(__t.string()),
  aspectRatio: __t.option(__t.string()).name("aspect_ratio"),
  status: __t.string(),
  requestedBy: __t.identity().name("requested_by"),
  error: __t.option(__t.string()),
  reservedVariants: __t.u8().name("reserved_variants"),
  claimedBy: __t.option(__t.identity()).name("claimed_by"),
  claimedAt: __t.option(__t.timestamp()).name("claimed_at"),
  createdAt: __t.timestamp().name("created_at"),
  finishedAt: __t.option(__t.timestamp()).name("finished_at"),
});
