// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  copyId: __t.string().primaryKey().name("copy_id"),
  campaignId: __t.string().name("campaign_id"),
  draft: __t.string(),
  headline: __t.string(),
  text: __t.string(),
  status: __t.string(),
  error: __t.option(__t.string()),
  requestedBy: __t.identity().name("requested_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
