// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  briefId: __t.string(),
  audienceLabel: __t.string(),
  tone: __t.string(),
  messageAngle: __t.string(),
  valueProps: __t.array(__t.string()),
  headlineOptions: __t.array(__t.string()),
  cta: __t.string(),
  visualCues: __t.array(__t.string()),
  visualAvoid: __t.array(__t.string()),
  format: __t.string(),
};
