// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  videoId: __t.string(),
  title: __t.string(),
  videoUrl: __t.string(),
  thumbnailUrl: __t.string(),
  durationS: __t.f64(),
  scriptJson: __t.string(),
  reviewJson: __t.string(),
};
