// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddAdminReducer from "./add_admin_reducer";
import AddOpsAdminReducer from "./add_ops_admin_reducer";
import AddSimCommentsReducer from "./add_sim_comments_reducer";
import AnswerTwinQuestionReducer from "./answer_twin_question_reducer";
import ApproveVariantReducer from "./approve_variant_reducer";
import ArchiveAudienceReducer from "./archive_audience_reducer";
import ArchiveProfilesReducer from "./archive_profiles_reducer";
import AskTwinReducer from "./ask_twin_reducer";
import AttachLabDraftMediaReducer from "./attach_lab_draft_media_reducer";
import AttachLabRunsReducer from "./attach_lab_runs_reducer";
import ClaimCreativeJobReducer from "./claim_creative_job_reducer";
import ClaimLabExperimentReducer from "./claim_lab_experiment_reducer";
import ClaimOnboardingReducer from "./claim_onboarding_reducer";
import ClaimTwinQuestionReducer from "./claim_twin_question_reducer";
import ClearBrandBaselineReducer from "./clear_brand_baseline_reducer";
import ClearVideoExpectationReducer from "./clear_video_expectation_reducer";
import CompleteIngestionRunReducer from "./complete_ingestion_run_reducer";
import CompleteTwinBuildRunReducer from "./complete_twin_build_run_reducer";
import CreateCampaignReducer from "./create_campaign_reducer";
import CreateSimRunReducer from "./create_sim_run_reducer";
import DeleteCampaignReducer from "./delete_campaign_reducer";
import EditBriefReducer from "./edit_brief_reducer";
import FailCampaignVideoReducer from "./fail_campaign_video_reducer";
import FailCreativeJobReducer from "./fail_creative_job_reducer";
import FailLabExperimentReducer from "./fail_lab_experiment_reducer";
import FailOnboardingReducer from "./fail_onboarding_reducer";
import FailSimRunReducer from "./fail_sim_run_reducer";
import FailTwinQuestionReducer from "./fail_twin_question_reducer";
import FinishCampaignVideoReducer from "./finish_campaign_video_reducer";
import FinishCreativeJobReducer from "./finish_creative_job_reducer";
import FinishLabExperimentReducer from "./finish_lab_experiment_reducer";
import HandoffCampaignReducer from "./handoff_campaign_reducer";
import HeartbeatCreativeJobReducer from "./heartbeat_creative_job_reducer";
import PublishBriefReducer from "./publish_brief_reducer";
import PublishTwinReducer from "./publish_twin_reducer";
import PurgeBrandReducer from "./purge_brand_reducer";
import RemoveOpsAdminReducer from "./remove_ops_admin_reducer";
import ReplaceAudienceEdgesReducer from "./replace_audience_edges_reducer";
import RequestCampaignVideoReducer from "./request_campaign_video_reducer";
import RequestCreativeReducer from "./request_creative_reducer";
import RequestDraftCopyReducer from "./request_draft_copy_reducer";
import RequestDraftVideoReducer from "./request_draft_video_reducer";
import RequestLabExperimentReducer from "./request_lab_experiment_reducer";
import RequestOnboardingReducer from "./request_onboarding_reducer";
import RequestTwinTopupReducer from "./request_twin_topup_reducer";
import RequestVideoEditReducer from "./request_video_edit_reducer";
import ResetImportedAudiencesReducer from "./reset_imported_audiences_reducer";
import ResetStaleCreativeJobsReducer from "./reset_stale_creative_jobs_reducer";
import RetireArchivedAudienceReducer from "./retire_archived_audience_reducer";
import RetryCreativeJobReducer from "./retry_creative_job_reducer";
import RetryOnboardingReducer from "./retry_onboarding_reducer";
import SetBacktestResultReducer from "./set_backtest_result_reducer";
import SetBrandBaselineReducer from "./set_brand_baseline_reducer";
import SetCampaignVideoProgressReducer from "./set_campaign_video_progress_reducer";
import SetDraftCopyReducer from "./set_draft_copy_reducer";
import SetOnboardingProgressReducer from "./set_onboarding_progress_reducer";
import SetOpsStateReducer from "./set_ops_state_reducer";
import SetSimCalibrationReducer from "./set_sim_calibration_reducer";
import SetSimProbsReducer from "./set_sim_probs_reducer";
import SetSimSettingsReducer from "./set_sim_settings_reducer";
import SetSimSignalProbsReducer from "./set_sim_signal_probs_reducer";
import SetTwinJobStatusReducer from "./set_twin_job_status_reducer";
import SetTwinTopupReducer from "./set_twin_topup_reducer";
import SetVariantCopyReducer from "./set_variant_copy_reducer";
import SetVideoExpectationReducer from "./set_video_expectation_reducer";
import SetVideoModeReducer from "./set_video_mode_reducer";
import SetVideoSettingsReducer from "./set_video_settings_reducer";
import SetXUserProfileImageReducer from "./set_x_user_profile_image_reducer";
import StarVariantReducer from "./star_variant_reducer";
import StartCampaignFlowReducer from "./start_campaign_flow_reducer";
import StartCampaignVideoReducer from "./start_campaign_video_reducer";
import StartCascadeReducer from "./start_cascade_reducer";
import StartIngestionRunReducer from "./start_ingestion_run_reducer";
import StartTwinBuildRunReducer from "./start_twin_build_run_reducer";
import UpdateCampaignFlowReducer from "./update_campaign_flow_reducer";
import UpdateIngestionRunReducer from "./update_ingestion_run_reducer";
import UpdateOnboardingBriefReducer from "./update_onboarding_brief_reducer";
import UpsertAudienceMembershipReducer from "./upsert_audience_membership_reducer";
import UpsertBrandKitReducer from "./upsert_brand_kit_reducer";
import UpsertContextAnnotationReducer from "./upsert_context_annotation_reducer";
import UpsertNicheReducer from "./upsert_niche_reducer";
import UpsertPostEntityReducer from "./upsert_post_entity_reducer";
import UpsertPostMediaReducer from "./upsert_post_media_reducer";
import UpsertPostReferenceReducer from "./upsert_post_reference_reducer";
import UpsertVariantReducer from "./upsert_variant_reducer";
import UpsertXPostReducer from "./upsert_x_post_reducer";
import UpsertXUserReducer from "./upsert_x_user_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AdVariantRow from "./ad_variant_table";
import ArchivedProfileRow from "./archived_profile_table";
import AudienceEdgeRow from "./audience_edge_table";
import AudienceMembershipRow from "./audience_membership_table";
import AudienceSnapshotRow from "./audience_snapshot_table";
import BacktestResultRow from "./backtest_result_table";
import BrandBaselineRow from "./brand_baseline_table";
import BrandKitRow from "./brand_kit_table";
import CampaignRow from "./campaign_table";
import CampaignDraftVideoRow from "./campaign_draft_video_table";
import CampaignFlowRow from "./campaign_flow_table";
import CampaignVideoRow from "./campaign_video_table";
import CreativeBriefRow from "./creative_brief_table";
import CreativeJobRow from "./creative_job_table";
import DraftCopyRow from "./draft_copy_table";
import LabDraftMediaRow from "./lab_draft_media_table";
import LabExperimentRow from "./lab_experiment_table";
import NicheRow from "./niche_table";
import OnboardingRow from "./onboarding_table";
import OpsAdminRow from "./ops_admin_table";
import OpsHiddenRow from "./ops_hidden_table";
import OpsStateRow from "./ops_state_table";
import SimCalibrationRow from "./sim_calibration_table";
import SimCommentRow from "./sim_comment_table";
import SimEventRow from "./sim_event_table";
import SimNodeRow from "./sim_node_table";
import SimNodeSignalRow from "./sim_node_signal_table";
import SimOutsideTickRow from "./sim_outside_tick_table";
import SimProbRow from "./sim_prob_table";
import SimProjectionRow from "./sim_projection_table";
import SimRunRow from "./sim_run_table";
import SimSettingsRow from "./sim_settings_table";
import SimSignalRow from "./sim_signal_table";
import SimSignalProbRow from "./sim_signal_prob_table";
import SimSignalSourceRow from "./sim_signal_source_table";
import TwinRow from "./twin_table";
import TwinAudienceRow from "./twin_audience_table";
import TwinBuildJobRow from "./twin_build_job_table";
import TwinBuildRunRow from "./twin_build_run_table";
import TwinNicheRow from "./twin_niche_table";
import TwinQuestionRow from "./twin_question_table";
import TwinTopupRow from "./twin_topup_table";
import VideoEditRow from "./video_edit_table";
import VideoExpectationRow from "./video_expectation_table";
import VideoModeRow from "./video_mode_table";
import VideoSettingsRow from "./video_settings_table";
import XContextAnnotationRow from "./x_context_annotation_table";
import XIngestionRunRow from "./x_ingestion_run_table";
import XPostRow from "./x_post_table";
import XPostEntityRow from "./x_post_entity_table";
import XPostMediaRow from "./x_post_media_table";
import XPostReferenceRow from "./x_post_reference_table";
import XUserRow from "./x_user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  adVariant: __table({
    name: 'ad_variant',
    indexes: [
      { accessor: 'briefId', name: 'ad_variant_brief_id_idx_btree', algorithm: 'btree', columns: [
        'briefId',
      ] },
      { accessor: 'campaignId', name: 'ad_variant_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
      { accessor: 'jobId', name: 'ad_variant_job_id_idx_btree', algorithm: 'btree', columns: [
        'jobId',
      ] },
      { accessor: 'status', name: 'ad_variant_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'variantId', name: 'ad_variant_variant_id_idx_btree', algorithm: 'btree', columns: [
        'variantId',
      ] },
    ],
    constraints: [
      { name: 'ad_variant_variant_id_key', constraint: 'unique', columns: ['variantId'] },
    ],
  }, AdVariantRow),
  archivedProfile: __table({
    name: 'archived_profile',
    indexes: [
      { accessor: 'userId', name: 'archived_profile_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'archived_profile_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, ArchivedProfileRow),
  audienceEdge: __table({
    name: 'audience_edge',
    indexes: [
      { accessor: 'brandUserId', name: 'audience_edge_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
      { accessor: 'edgeId', name: 'audience_edge_edge_id_idx_btree', algorithm: 'btree', columns: [
        'edgeId',
      ] },
    ],
    constraints: [
      { name: 'audience_edge_edge_id_key', constraint: 'unique', columns: ['edgeId'] },
    ],
  }, AudienceEdgeRow),
  audienceMembership: __table({
    name: 'audience_membership',
    indexes: [
      { accessor: 'by_brand_follower', name: 'audience_membership_brand_user_id_follower_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
        'followerUserId',
      ] },
      { accessor: 'followerUserId', name: 'audience_membership_follower_user_id_idx_btree', algorithm: 'btree', columns: [
        'followerUserId',
      ] },
      { accessor: 'membershipId', name: 'audience_membership_membership_id_idx_btree', algorithm: 'btree', columns: [
        'membershipId',
      ] },
    ],
    constraints: [
      { name: 'audience_membership_membership_id_key', constraint: 'unique', columns: ['membershipId'] },
    ],
  }, AudienceMembershipRow),
  audienceSnapshot: __table({
    name: 'audience_snapshot',
    indexes: [
      { accessor: 'brand', name: 'audience_snapshot_brand_idx_btree', algorithm: 'btree', columns: [
        'brand',
      ] },
      { accessor: 'snapshotId', name: 'audience_snapshot_snapshot_id_idx_btree', algorithm: 'btree', columns: [
        'snapshotId',
      ] },
    ],
    constraints: [
      { name: 'audience_snapshot_snapshot_id_key', constraint: 'unique', columns: ['snapshotId'] },
    ],
  }, AudienceSnapshotRow),
  backtestResult: __table({
    name: 'backtest_result',
    indexes: [
      { accessor: 'backtestResultId', name: 'backtest_result_backtest_result_id_idx_btree', algorithm: 'btree', columns: [
        'backtestResultId',
      ] },
    ],
    constraints: [
      { name: 'backtest_result_backtest_result_id_key', constraint: 'unique', columns: ['backtestResultId'] },
    ],
  }, BacktestResultRow),
  brandBaseline: __table({
    name: 'brand_baseline',
    indexes: [
      { accessor: 'brandUserId', name: 'brand_baseline_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
    ],
    constraints: [
      { name: 'brand_baseline_brand_user_id_key', constraint: 'unique', columns: ['brandUserId'] },
    ],
  }, BrandBaselineRow),
  brandKit: __table({
    name: 'brand_kit',
    indexes: [
      { accessor: 'brandUserId', name: 'brand_kit_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
    ],
    constraints: [
      { name: 'brand_kit_brand_user_id_key', constraint: 'unique', columns: ['brandUserId'] },
    ],
  }, BrandKitRow),
  campaign: __table({
    name: 'campaign',
    indexes: [
      { accessor: 'brandUserId', name: 'campaign_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
      { accessor: 'campaignId', name: 'campaign_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
    ],
    constraints: [
      { name: 'campaign_campaign_id_key', constraint: 'unique', columns: ['campaignId'] },
    ],
  }, CampaignRow),
  campaignDraftVideo: __table({
    name: 'campaign_draft_video',
    indexes: [
      { accessor: 'campaignId', name: 'campaign_draft_video_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
      { accessor: 'linkId', name: 'campaign_draft_video_link_id_idx_btree', algorithm: 'btree', columns: [
        'linkId',
      ] },
    ],
    constraints: [
      { name: 'campaign_draft_video_link_id_key', constraint: 'unique', columns: ['linkId'] },
    ],
  }, CampaignDraftVideoRow),
  campaignFlow: __table({
    name: 'campaign_flow',
    indexes: [
      { accessor: 'brand', name: 'campaign_flow_brand_idx_btree', algorithm: 'btree', columns: [
        'brand',
      ] },
      { accessor: 'campaignId', name: 'campaign_flow_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
      { accessor: 'requestedBy', name: 'campaign_flow_requested_by_idx_btree', algorithm: 'btree', columns: [
        'requestedBy',
      ] },
    ],
    constraints: [
      { name: 'campaign_flow_campaign_id_key', constraint: 'unique', columns: ['campaignId'] },
    ],
  }, CampaignFlowRow),
  campaignVideo: __table({
    name: 'campaign_video',
    indexes: [
      { accessor: 'brand', name: 'campaign_video_brand_idx_btree', algorithm: 'btree', columns: [
        'brand',
      ] },
      { accessor: 'status', name: 'campaign_video_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'videoId', name: 'campaign_video_video_id_idx_btree', algorithm: 'btree', columns: [
        'videoId',
      ] },
    ],
    constraints: [
      { name: 'campaign_video_video_id_key', constraint: 'unique', columns: ['videoId'] },
    ],
  }, CampaignVideoRow),
  creativeBrief: __table({
    name: 'creative_brief',
    indexes: [
      { accessor: 'briefId', name: 'creative_brief_brief_id_idx_btree', algorithm: 'btree', columns: [
        'briefId',
      ] },
      { accessor: 'campaignId', name: 'creative_brief_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
    ],
    constraints: [
      { name: 'creative_brief_brief_id_key', constraint: 'unique', columns: ['briefId'] },
    ],
  }, CreativeBriefRow),
  creativeJob: __table({
    name: 'creative_job',
    indexes: [
      { accessor: 'campaignId', name: 'creative_job_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
      { accessor: 'jobId', name: 'creative_job_job_id_idx_btree', algorithm: 'btree', columns: [
        'jobId',
      ] },
      { accessor: 'status', name: 'creative_job_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'creative_job_job_id_key', constraint: 'unique', columns: ['jobId'] },
    ],
  }, CreativeJobRow),
  draftCopy: __table({
    name: 'draft_copy',
    indexes: [
      { accessor: 'campaignId', name: 'draft_copy_campaign_id_idx_btree', algorithm: 'btree', columns: [
        'campaignId',
      ] },
      { accessor: 'copyId', name: 'draft_copy_copy_id_idx_btree', algorithm: 'btree', columns: [
        'copyId',
      ] },
      { accessor: 'status', name: 'draft_copy_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'draft_copy_copy_id_key', constraint: 'unique', columns: ['copyId'] },
    ],
  }, DraftCopyRow),
  labDraftMedia: __table({
    name: 'lab_draft_media',
    indexes: [
      { accessor: 'experimentId', name: 'lab_draft_media_experiment_id_idx_btree', algorithm: 'btree', columns: [
        'experimentId',
      ] },
      { accessor: 'mediaId', name: 'lab_draft_media_media_id_idx_btree', algorithm: 'btree', columns: [
        'mediaId',
      ] },
    ],
    constraints: [
      { name: 'lab_draft_media_media_id_key', constraint: 'unique', columns: ['mediaId'] },
    ],
  }, LabDraftMediaRow),
  labExperiment: __table({
    name: 'lab_experiment',
    indexes: [
      { accessor: 'brandUserId', name: 'lab_experiment_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
      { accessor: 'experimentId', name: 'lab_experiment_experiment_id_idx_btree', algorithm: 'btree', columns: [
        'experimentId',
      ] },
      { accessor: 'status', name: 'lab_experiment_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'lab_experiment_experiment_id_key', constraint: 'unique', columns: ['experimentId'] },
    ],
  }, LabExperimentRow),
  niche: __table({
    name: 'niche',
    indexes: [
      { accessor: 'slug', name: 'niche_slug_idx_btree', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'niche_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, NicheRow),
  onboarding: __table({
    name: 'onboarding',
    indexes: [
      { accessor: 'onboardingId', name: 'onboarding_onboarding_id_idx_btree', algorithm: 'btree', columns: [
        'onboardingId',
      ] },
      { accessor: 'requestedBy', name: 'onboarding_requested_by_idx_btree', algorithm: 'btree', columns: [
        'requestedBy',
      ] },
      { accessor: 'status', name: 'onboarding_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'onboarding_onboarding_id_key', constraint: 'unique', columns: ['onboardingId'] },
    ],
  }, OnboardingRow),
  opsAdmin: __table({
    name: 'ops_admin',
    indexes: [
      { accessor: 'identity', name: 'ops_admin_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'ops_admin_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, OpsAdminRow),
  opsHidden: __table({
    name: 'ops_hidden',
    indexes: [
      { accessor: 'key', name: 'ops_hidden_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'ops_hidden_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, OpsHiddenRow),
  opsState: __table({
    name: 'ops_state',
    indexes: [
      { accessor: 'key', name: 'ops_state_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'ops_state_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, OpsStateRow),
  simCalibration: __table({
    name: 'sim_calibration',
    indexes: [
      { accessor: 'scope', name: 'sim_calibration_scope_idx_btree', algorithm: 'btree', columns: [
        'scope',
      ] },
    ],
    constraints: [
      { name: 'sim_calibration_scope_key', constraint: 'unique', columns: ['scope'] },
    ],
  }, SimCalibrationRow),
  simComment: __table({
    name: 'sim_comment',
    indexes: [
      { accessor: 'runId', name: 'sim_comment_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simCommentId', name: 'sim_comment_sim_comment_id_idx_btree', algorithm: 'btree', columns: [
        'simCommentId',
      ] },
    ],
    constraints: [
      { name: 'sim_comment_sim_comment_id_key', constraint: 'unique', columns: ['simCommentId'] },
    ],
  }, SimCommentRow),
  simEvent: __table({
    name: 'sim_event',
    indexes: [
      { accessor: 'runId', name: 'sim_event_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simEventId', name: 'sim_event_sim_event_id_idx_btree', algorithm: 'btree', columns: [
        'simEventId',
      ] },
    ],
    constraints: [
      { name: 'sim_event_sim_event_id_key', constraint: 'unique', columns: ['simEventId'] },
    ],
  }, SimEventRow),
  simNode: __table({
    name: 'sim_node',
    indexes: [
      { accessor: 'runId', name: 'sim_node_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simNodeId', name: 'sim_node_sim_node_id_idx_btree', algorithm: 'btree', columns: [
        'simNodeId',
      ] },
    ],
    constraints: [
      { name: 'sim_node_sim_node_id_key', constraint: 'unique', columns: ['simNodeId'] },
    ],
  }, SimNodeRow),
  simNodeSignal: __table({
    name: 'sim_node_signal',
    indexes: [
      { accessor: 'runId', name: 'sim_node_signal_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simNodeSignalId', name: 'sim_node_signal_sim_node_signal_id_idx_btree', algorithm: 'btree', columns: [
        'simNodeSignalId',
      ] },
    ],
    constraints: [
      { name: 'sim_node_signal_sim_node_signal_id_key', constraint: 'unique', columns: ['simNodeSignalId'] },
    ],
  }, SimNodeSignalRow),
  simOutsideTick: __table({
    name: 'sim_outside_tick',
    indexes: [
      { accessor: 'runId', name: 'sim_outside_tick_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simOutsideTickId', name: 'sim_outside_tick_sim_outside_tick_id_idx_btree', algorithm: 'btree', columns: [
        'simOutsideTickId',
      ] },
    ],
    constraints: [
      { name: 'sim_outside_tick_sim_outside_tick_id_key', constraint: 'unique', columns: ['simOutsideTickId'] },
    ],
  }, SimOutsideTickRow),
  simProb: __table({
    name: 'sim_prob',
    indexes: [
      { accessor: 'runId', name: 'sim_prob_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simProbId', name: 'sim_prob_sim_prob_id_idx_btree', algorithm: 'btree', columns: [
        'simProbId',
      ] },
    ],
    constraints: [
      { name: 'sim_prob_sim_prob_id_key', constraint: 'unique', columns: ['simProbId'] },
    ],
  }, SimProbRow),
  simProjection: __table({
    name: 'sim_projection',
    indexes: [
      { accessor: 'runId', name: 'sim_projection_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
    ],
    constraints: [
      { name: 'sim_projection_run_id_key', constraint: 'unique', columns: ['runId'] },
    ],
  }, SimProjectionRow),
  simRun: __table({
    name: 'sim_run',
    indexes: [
      { accessor: 'brandUserId', name: 'sim_run_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
      { accessor: 'runId', name: 'sim_run_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
    ],
    constraints: [
      { name: 'sim_run_run_id_key', constraint: 'unique', columns: ['runId'] },
    ],
  }, SimRunRow),
  simSettings: __table({
    name: 'sim_settings',
    indexes: [
      { accessor: 'key', name: 'sim_settings_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'sim_settings_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SimSettingsRow),
  simSignal: __table({
    name: 'sim_signal',
    indexes: [
      { accessor: 'runId', name: 'sim_signal_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simSignalId', name: 'sim_signal_sim_signal_id_idx_btree', algorithm: 'btree', columns: [
        'simSignalId',
      ] },
    ],
    constraints: [
      { name: 'sim_signal_sim_signal_id_key', constraint: 'unique', columns: ['simSignalId'] },
    ],
  }, SimSignalRow),
  simSignalProb: __table({
    name: 'sim_signal_prob',
    indexes: [
      { accessor: 'runId', name: 'sim_signal_prob_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simSignalProbId', name: 'sim_signal_prob_sim_signal_prob_id_idx_btree', algorithm: 'btree', columns: [
        'simSignalProbId',
      ] },
    ],
    constraints: [
      { name: 'sim_signal_prob_sim_signal_prob_id_key', constraint: 'unique', columns: ['simSignalProbId'] },
    ],
  }, SimSignalProbRow),
  simSignalSource: __table({
    name: 'sim_signal_source',
    indexes: [
      { accessor: 'runId', name: 'sim_signal_source_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'simSignalSourceId', name: 'sim_signal_source_sim_signal_source_id_idx_btree', algorithm: 'btree', columns: [
        'simSignalSourceId',
      ] },
    ],
    constraints: [
      { name: 'sim_signal_source_sim_signal_source_id_key', constraint: 'unique', columns: ['simSignalSourceId'] },
    ],
  }, SimSignalSourceRow),
  twin: __table({
    name: 'twin',
    indexes: [
      { accessor: 'brandUserId', name: 'twin_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
      { accessor: 'userId', name: 'twin_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
      { accessor: 'username', name: 'twin_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'twin_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, TwinRow),
  twinAudience: __table({
    name: 'twin_audience',
    indexes: [
      { accessor: 'brandUserId', name: 'twin_audience_brand_user_id_idx_btree', algorithm: 'btree', columns: [
        'brandUserId',
      ] },
      { accessor: 'twinAudienceId', name: 'twin_audience_twin_audience_id_idx_btree', algorithm: 'btree', columns: [
        'twinAudienceId',
      ] },
      { accessor: 'userId', name: 'twin_audience_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'twin_audience_twin_audience_id_key', constraint: 'unique', columns: ['twinAudienceId'] },
    ],
  }, TwinAudienceRow),
  twinBuildJob: __table({
    name: 'twin_build_job',
    indexes: [
      { accessor: 'jobId', name: 'twin_build_job_job_id_idx_btree', algorithm: 'btree', columns: [
        'jobId',
      ] },
      { accessor: 'runId', name: 'twin_build_job_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
    ],
    constraints: [
      { name: 'twin_build_job_job_id_key', constraint: 'unique', columns: ['jobId'] },
    ],
  }, TwinBuildJobRow),
  twinBuildRun: __table({
    name: 'twin_build_run',
    indexes: [
      { accessor: 'runId', name: 'twin_build_run_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
    ],
    constraints: [
      { name: 'twin_build_run_run_id_key', constraint: 'unique', columns: ['runId'] },
    ],
  }, TwinBuildRunRow),
  twinNiche: __table({
    name: 'twin_niche',
    indexes: [
      { accessor: 'niche', name: 'twin_niche_niche_idx_btree', algorithm: 'btree', columns: [
        'niche',
      ] },
      { accessor: 'twinNicheId', name: 'twin_niche_twin_niche_id_idx_btree', algorithm: 'btree', columns: [
        'twinNicheId',
      ] },
      { accessor: 'userId', name: 'twin_niche_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'twin_niche_twin_niche_id_key', constraint: 'unique', columns: ['twinNicheId'] },
    ],
  }, TwinNicheRow),
  twinQuestion: __table({
    name: 'twin_question',
    indexes: [
      { accessor: 'questionId', name: 'twin_question_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
      { accessor: 'status', name: 'twin_question_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'userId', name: 'twin_question_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'twin_question_question_id_key', constraint: 'unique', columns: ['questionId'] },
    ],
  }, TwinQuestionRow),
  twinTopup: __table({
    name: 'twin_topup',
    indexes: [
      { accessor: 'status', name: 'twin_topup_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'topupId', name: 'twin_topup_topup_id_idx_btree', algorithm: 'btree', columns: [
        'topupId',
      ] },
    ],
    constraints: [
      { name: 'twin_topup_topup_id_key', constraint: 'unique', columns: ['topupId'] },
    ],
  }, TwinTopupRow),
  videoEdit: __table({
    name: 'video_edit',
    indexes: [
      { accessor: 'videoId', name: 'video_edit_video_id_idx_btree', algorithm: 'btree', columns: [
        'videoId',
      ] },
    ],
    constraints: [
      { name: 'video_edit_video_id_key', constraint: 'unique', columns: ['videoId'] },
    ],
  }, VideoEditRow),
  videoExpectation: __table({
    name: 'video_expectation',
    indexes: [
      { accessor: 'videoId', name: 'video_expectation_video_id_idx_btree', algorithm: 'btree', columns: [
        'videoId',
      ] },
    ],
    constraints: [
      { name: 'video_expectation_video_id_key', constraint: 'unique', columns: ['videoId'] },
    ],
  }, VideoExpectationRow),
  videoMode: __table({
    name: 'video_mode',
    indexes: [
      { accessor: 'key', name: 'video_mode_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'video_mode_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, VideoModeRow),
  videoSettings: __table({
    name: 'video_settings',
    indexes: [
      { accessor: 'key', name: 'video_settings_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'video_settings_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, VideoSettingsRow),
  xContextAnnotation: __table({
    name: 'x_context_annotation',
    indexes: [
      { accessor: 'annotationId', name: 'x_context_annotation_annotation_id_idx_btree', algorithm: 'btree', columns: [
        'annotationId',
      ] },
      { accessor: 'postId', name: 'x_context_annotation_post_id_idx_btree', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'x_context_annotation_annotation_id_key', constraint: 'unique', columns: ['annotationId'] },
    ],
  }, XContextAnnotationRow),
  xIngestionRun: __table({
    name: 'x_ingestion_run',
    indexes: [
      { accessor: 'ingestionRunId', name: 'x_ingestion_run_ingestion_run_id_idx_btree', algorithm: 'btree', columns: [
        'ingestionRunId',
      ] },
    ],
    constraints: [
      { name: 'x_ingestion_run_ingestion_run_id_key', constraint: 'unique', columns: ['ingestionRunId'] },
    ],
  }, XIngestionRunRow),
  xPost: __table({
    name: 'x_post',
    indexes: [
      { accessor: 'authorUserId', name: 'x_post_author_user_id_idx_btree', algorithm: 'btree', columns: [
        'authorUserId',
      ] },
      { accessor: 'createdAt', name: 'x_post_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'postId', name: 'x_post_post_id_idx_btree', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'x_post_post_id_key', constraint: 'unique', columns: ['postId'] },
    ],
  }, XPostRow),
  xPostEntity: __table({
    name: 'x_post_entity',
    indexes: [
      { accessor: 'entityId', name: 'x_post_entity_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'postId', name: 'x_post_entity_post_id_idx_btree', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'x_post_entity_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, XPostEntityRow),
  xPostMedia: __table({
    name: 'x_post_media',
    indexes: [
      { accessor: 'id', name: 'x_post_media_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'postId', name: 'x_post_media_post_id_idx_btree', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'x_post_media_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, XPostMediaRow),
  xPostReference: __table({
    name: 'x_post_reference',
    indexes: [
      { accessor: 'id', name: 'x_post_reference_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'postId', name: 'x_post_reference_post_id_idx_btree', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'x_post_reference_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, XPostReferenceRow),
  xUser: __table({
    name: 'x_user',
    indexes: [
      { accessor: 'userId', name: 'x_user_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
      { accessor: 'username', name: 'x_user_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'x_user_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, XUserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_admin", AddAdminReducer),
  __reducerSchema("add_ops_admin", AddOpsAdminReducer),
  __reducerSchema("add_sim_comments", AddSimCommentsReducer),
  __reducerSchema("answer_twin_question", AnswerTwinQuestionReducer),
  __reducerSchema("approve_variant", ApproveVariantReducer),
  __reducerSchema("archive_audience", ArchiveAudienceReducer),
  __reducerSchema("archive_profiles", ArchiveProfilesReducer),
  __reducerSchema("ask_twin", AskTwinReducer),
  __reducerSchema("attach_lab_draft_media", AttachLabDraftMediaReducer),
  __reducerSchema("attach_lab_runs", AttachLabRunsReducer),
  __reducerSchema("claim_creative_job", ClaimCreativeJobReducer),
  __reducerSchema("claim_lab_experiment", ClaimLabExperimentReducer),
  __reducerSchema("claim_onboarding", ClaimOnboardingReducer),
  __reducerSchema("claim_twin_question", ClaimTwinQuestionReducer),
  __reducerSchema("clear_brand_baseline", ClearBrandBaselineReducer),
  __reducerSchema("clear_video_expectation", ClearVideoExpectationReducer),
  __reducerSchema("complete_ingestion_run", CompleteIngestionRunReducer),
  __reducerSchema("complete_twin_build_run", CompleteTwinBuildRunReducer),
  __reducerSchema("create_campaign", CreateCampaignReducer),
  __reducerSchema("create_sim_run", CreateSimRunReducer),
  __reducerSchema("delete_campaign", DeleteCampaignReducer),
  __reducerSchema("edit_brief", EditBriefReducer),
  __reducerSchema("fail_campaign_video", FailCampaignVideoReducer),
  __reducerSchema("fail_creative_job", FailCreativeJobReducer),
  __reducerSchema("fail_lab_experiment", FailLabExperimentReducer),
  __reducerSchema("fail_onboarding", FailOnboardingReducer),
  __reducerSchema("fail_sim_run", FailSimRunReducer),
  __reducerSchema("fail_twin_question", FailTwinQuestionReducer),
  __reducerSchema("finish_campaign_video", FinishCampaignVideoReducer),
  __reducerSchema("finish_creative_job", FinishCreativeJobReducer),
  __reducerSchema("finish_lab_experiment", FinishLabExperimentReducer),
  __reducerSchema("handoff_campaign", HandoffCampaignReducer),
  __reducerSchema("heartbeat_creative_job", HeartbeatCreativeJobReducer),
  __reducerSchema("publish_brief", PublishBriefReducer),
  __reducerSchema("publish_twin", PublishTwinReducer),
  __reducerSchema("purge_brand", PurgeBrandReducer),
  __reducerSchema("remove_ops_admin", RemoveOpsAdminReducer),
  __reducerSchema("replace_audience_edges", ReplaceAudienceEdgesReducer),
  __reducerSchema("request_campaign_video", RequestCampaignVideoReducer),
  __reducerSchema("request_creative", RequestCreativeReducer),
  __reducerSchema("request_draft_copy", RequestDraftCopyReducer),
  __reducerSchema("request_draft_video", RequestDraftVideoReducer),
  __reducerSchema("request_lab_experiment", RequestLabExperimentReducer),
  __reducerSchema("request_onboarding", RequestOnboardingReducer),
  __reducerSchema("request_twin_topup", RequestTwinTopupReducer),
  __reducerSchema("request_video_edit", RequestVideoEditReducer),
  __reducerSchema("reset_imported_audiences", ResetImportedAudiencesReducer),
  __reducerSchema("reset_stale_creative_jobs", ResetStaleCreativeJobsReducer),
  __reducerSchema("retire_archived_audience", RetireArchivedAudienceReducer),
  __reducerSchema("retry_creative_job", RetryCreativeJobReducer),
  __reducerSchema("retry_onboarding", RetryOnboardingReducer),
  __reducerSchema("set_backtest_result", SetBacktestResultReducer),
  __reducerSchema("set_brand_baseline", SetBrandBaselineReducer),
  __reducerSchema("set_campaign_video_progress", SetCampaignVideoProgressReducer),
  __reducerSchema("set_draft_copy", SetDraftCopyReducer),
  __reducerSchema("set_onboarding_progress", SetOnboardingProgressReducer),
  __reducerSchema("set_ops_state", SetOpsStateReducer),
  __reducerSchema("set_sim_calibration", SetSimCalibrationReducer),
  __reducerSchema("set_sim_probs", SetSimProbsReducer),
  __reducerSchema("set_sim_settings", SetSimSettingsReducer),
  __reducerSchema("set_sim_signal_probs", SetSimSignalProbsReducer),
  __reducerSchema("set_twin_job_status", SetTwinJobStatusReducer),
  __reducerSchema("set_twin_topup", SetTwinTopupReducer),
  __reducerSchema("set_variant_copy", SetVariantCopyReducer),
  __reducerSchema("set_video_expectation", SetVideoExpectationReducer),
  __reducerSchema("set_video_mode", SetVideoModeReducer),
  __reducerSchema("set_video_settings", SetVideoSettingsReducer),
  __reducerSchema("set_x_user_profile_image", SetXUserProfileImageReducer),
  __reducerSchema("star_variant", StarVariantReducer),
  __reducerSchema("start_campaign_flow", StartCampaignFlowReducer),
  __reducerSchema("start_campaign_video", StartCampaignVideoReducer),
  __reducerSchema("start_cascade", StartCascadeReducer),
  __reducerSchema("start_ingestion_run", StartIngestionRunReducer),
  __reducerSchema("start_twin_build_run", StartTwinBuildRunReducer),
  __reducerSchema("update_campaign_flow", UpdateCampaignFlowReducer),
  __reducerSchema("update_ingestion_run", UpdateIngestionRunReducer),
  __reducerSchema("update_onboarding_brief", UpdateOnboardingBriefReducer),
  __reducerSchema("upsert_audience_membership", UpsertAudienceMembershipReducer),
  __reducerSchema("upsert_brand_kit", UpsertBrandKitReducer),
  __reducerSchema("upsert_context_annotation", UpsertContextAnnotationReducer),
  __reducerSchema("upsert_niche", UpsertNicheReducer),
  __reducerSchema("upsert_post_entity", UpsertPostEntityReducer),
  __reducerSchema("upsert_post_media", UpsertPostMediaReducer),
  __reducerSchema("upsert_post_reference", UpsertPostReferenceReducer),
  __reducerSchema("upsert_variant", UpsertVariantReducer),
  __reducerSchema("upsert_x_post", UpsertXPostReducer),
  __reducerSchema("upsert_x_user", UpsertXUserReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

