// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  onboardingId: __t.u64().primaryKey().name("onboarding_id"),
  handle: __t.string(),
  brandUserId: __t.string().name("brand_user_id"),
  status: __t.string(),
  ingestionRunId: __t.string().name("ingestion_run_id"),
  twinRunId: __t.string().name("twin_run_id"),
  ownerName: __t.string().name("owner_name"),
  role: __t.string(),
  campaignName: __t.string().name("campaign_name"),
  campaignNews: __t.string().name("campaign_news"),
  goal: __t.string(),
  error: __t.option(__t.string()),
  requestedBy: __t.identity().name("requested_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
