// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  BriefTheme,
} from "./types";

export default {
  jobId: __t.u64(),
  briefId: __t.string(),
  campaignId: __t.string(),
  segment: __t.string(),
  version: __t.u32(),
  audienceLabel: __t.string(),
  share: __t.f64(),
  twinCount: __t.u32(),
  get keyInterests() {
    return __t.array(BriefTheme);
  },
  get avoid() {
    return __t.array(BriefTheme);
  },
  tone: __t.string(),
  messageAngle: __t.string(),
  valueProps: __t.array(__t.string()),
  headlineOptions: __t.array(__t.string()),
  cta: __t.string(),
  visualCues: __t.array(__t.string()),
  visualAvoid: __t.array(__t.string()),
  format: __t.string(),
  model: __t.string(),
  evidenceJson: __t.option(__t.string()),
};
