// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TwinTopic,
} from "./types";

export default {
  runId: __t.string(),
  userId: __t.string(),
  username: __t.string(),
  brandUserId: __t.string(),
  postCount: __t.u32(),
  replyShare: __t.f64(),
  quoteShare: __t.f64(),
  mentionRate: __t.f64(),
  avgLikes: __t.f64(),
  avgImpressions: __t.f64(),
  engagementRate: __t.f64(),
  activeHoursUtc: __t.byteArray(),
  get topics() {
    return __t.array(TwinTopic);
  },
  tone: __t.string(),
  personaSummary: __t.string(),
  hotButtons: __t.array(__t.string()),
  ignores: __t.array(__t.string()),
  formatPrefs: __t.array(__t.string()),
  evidencePostIds: __t.array(__t.string()),
  model: __t.string(),
};
