// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  brandUserId: __t.string(),
  posts: __t.u32(),
  likes: __t.f64(),
  reposts: __t.f64(),
  replies: __t.f64(),
  quotes: __t.f64(),
  views: __t.f64(),
  likeScale: __t.f64(),
  repostScale: __t.f64(),
  replyScale: __t.f64(),
  quoteScale: __t.f64(),
  viewScale: __t.f64(),
  baselineRunId: __t.string(),
  note: __t.string(),
};
