// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  scope: __t.string(),
  feedReach: __t.f64(),
  shareReach: __t.f64(),
  likeScale: __t.f64(),
  repostScale: __t.f64(),
  replyScale: __t.f64(),
  quoteScale: __t.f64(),
  source: __t.string(),
  note: __t.string(),
};
