// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  simSignalProbId: __t.string().primaryKey().name("sim_signal_prob_id"),
  runId: __t.string().name("run_id"),
  userId: __t.string().name("user_id"),
  pLike: __t.f64().name("p_like"),
  pRepost: __t.f64().name("p_repost"),
  pReply: __t.f64().name("p_reply"),
  pQuote: __t.f64().name("p_quote"),
});
