// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  simOutsideTickId: __t.string().primaryKey().name("sim_outside_tick_id"),
  runId: __t.string().name("run_id"),
  tick: __t.u32(),
  views: __t.u32(),
  likes: __t.u32(),
  reposts: __t.u32(),
  replies: __t.u32(),
  quotes: __t.u32(),
});
