// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  simSignalId: __t.string().primaryKey().name("sim_signal_id"),
  runId: __t.string().name("run_id"),
  signal: __t.string(),
  p10: __t.u32().name("p_10"),
  p50: __t.u32().name("p_50"),
  p90: __t.u32().name("p_90"),
  mean: __t.f64(),
});
