// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  simProbId: __t.string().primaryKey().name("sim_prob_id"),
  runId: __t.string().name("run_id"),
  userId: __t.string().name("user_id"),
  pEngage: __t.f64().name("p_engage"),
  action: __t.string(),
  reason: __t.string(),
});
