// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scope: __t.string().primaryKey(),
  feedReach: __t.f64().name("feed_reach"),
  shareReach: __t.f64().name("share_reach"),
  likeScale: __t.f64().name("like_scale"),
  repostScale: __t.f64().name("repost_scale"),
  replyScale: __t.f64().name("reply_scale"),
  quoteScale: __t.f64().name("quote_scale"),
  source: __t.string(),
  note: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
