// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  simNodeSignalId: __t.string().primaryKey().name("sim_node_signal_id"),
  runId: __t.string().name("run_id"),
  userId: __t.string().name("user_id"),
  likeShare: __t.f64().name("like_share"),
  repostShare: __t.f64().name("repost_share"),
  replyShare: __t.f64().name("reply_share"),
  quoteShare: __t.f64().name("quote_share"),
});
