// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  brandUserId: __t.string().name("brand_user_id"),
  draft: __t.string(),
  status: __t.string(),
  people: __t.u32(),
  trials: __t.u32(),
  reachP10: __t.u32().name("reach_p_10"),
  reachP50: __t.u32().name("reach_p_50"),
  reachP90: __t.u32().name("reach_p_90"),
  seenP50: __t.u32().name("seen_p_50"),
  replayTick: __t.u32().name("replay_tick"),
  replayMaxTick: __t.u32().name("replay_max_tick"),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
