// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  twinsPerBrand: __t.u32().name("twins_per_brand"),
  followersScraped: __t.u32().name("followers_scraped"),
  simTwins: __t.u32().name("sim_twins"),
  scaleMode: __t.string().name("scale_mode"),
  fillReplies: __t.u32().name("fill_replies"),
  updatedAt: __t.timestamp().name("updated_at"),
});
