// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  simNodeId: __t.string().primaryKey().name("sim_node_id"),
  runId: __t.string().name("run_id"),
  userId: __t.string().name("user_id"),
  engagedShare: __t.f64().name("engaged_share"),
  seenShare: __t.f64().name("seen_share"),
  replaySeenTick: __t.option(__t.u32()).name("replay_seen_tick"),
  replayEngagedTick: __t.option(__t.u32()).name("replay_engaged_tick"),
});
