// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TwinTopic,
} from "./types";


export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  username: __t.string(),
  brandUserId: __t.string().name("brand_user_id"),
  postCount: __t.u32().name("post_count"),
  replyShare: __t.f64().name("reply_share"),
  quoteShare: __t.f64().name("quote_share"),
  mentionRate: __t.f64().name("mention_rate"),
  avgLikes: __t.f64().name("avg_likes"),
  avgImpressions: __t.f64().name("avg_impressions"),
  engagementRate: __t.f64().name("engagement_rate"),
  activeHoursUtc: __t.byteArray().name("active_hours_utc"),
  get topics() {
    return __t.array(TwinTopic);
  },
  tone: __t.string(),
  personaSummary: __t.string().name("persona_summary"),
  hotButtons: __t.array(__t.string()).name("hot_buttons"),
  ignores: __t.array(__t.string()),
  formatPrefs: __t.array(__t.string()).name("format_prefs"),
  evidencePostIds: __t.array(__t.string()).name("evidence_post_ids"),
  model: __t.string(),
  buildRunId: __t.string().name("build_run_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
