// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  twinAudienceId: __t.string().primaryKey().name("twin_audience_id"),
  brandUserId: __t.string().name("brand_user_id"),
  userId: __t.string().name("user_id"),
  lastBuildRunId: __t.string().name("last_build_run_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
