// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questionId: __t.u64().primaryKey().name("question_id"),
  userId: __t.string().name("user_id"),
  draft: __t.string(),
  question: __t.string(),
  askedBy: __t.identity().name("asked_by"),
  status: __t.string(),
  action: __t.option(__t.string()),
  confidence: __t.option(__t.f64()),
  answer: __t.option(__t.string()),
  citedPostIds: __t.array(__t.string()).name("cited_post_ids"),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  answeredAt: __t.option(__t.timestamp()).name("answered_at"),
});
