// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.string().primaryKey().name("job_id"),
  runId: __t.string().name("run_id"),
  userId: __t.string().name("user_id"),
  username: __t.string(),
  status: __t.string(),
  error: __t.option(__t.string()),
  updatedAt: __t.timestamp().name("updated_at"),
});
