// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  brandUserId: __t.string().name("brand_user_id"),
  status: __t.string(),
  requested: __t.u32(),
  ready: __t.u32(),
  failed: __t.u32(),
  skipped: __t.u32(),
  startedAt: __t.timestamp().name("started_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
