// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdVariant = __t.object("AdVariant", {
  jobId: __t.u64(),
  variantId: __t.string(),
  campaignId: __t.string(),
  briefId: __t.string(),
  parentVariantId: __t.option(__t.string()),
  rootVariantId: __t.string(),
  depth: __t.u8(),
  operation: __t.string(),
  instruction: __t.option(__t.string()),
  imagePrompt: __t.string(),
  headline: __t.string(),
  cta: __t.string(),
  aspectRatio: __t.string(),
  model: __t.string(),
  quality: __t.string(),
  status: __t.string(),
  imageUrl: __t.option(__t.string()),
  xaiFileId: __t.option(__t.string()),
  costUsdTicks: __t.u64(),
  error: __t.option(__t.string()),
  starred: __t.bool(),
  approved: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AdVariant = __Infer<typeof AdVariant>;

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

export const AudienceEdge = __t.object("AudienceEdge", {
  edgeId: __t.string(),
  brandUserId: __t.string(),
  a: __t.string(),
  b: __t.string(),
  kind: __t.string(),
});
export type AudienceEdge = __Infer<typeof AudienceEdge>;

export const AudienceMembership = __t.object("AudienceMembership", {
  membershipId: __t.string(),
  brandUserId: __t.string(),
  followerUserId: __t.string(),
  discoveredAt: __t.timestamp(),
  ingestionRunId: __t.string(),
  source: __t.string(),
});
export type AudienceMembership = __Infer<typeof AudienceMembership>;

export const BacktestResult = __t.object("BacktestResult", {
  backtestResultId: __t.string(),
  scope: __t.string(),
  metric: __t.string(),
  value: __t.f64(),
  baseline: __t.f64(),
  n: __t.u32(),
  note: __t.string(),
  updatedAt: __t.timestamp(),
});
export type BacktestResult = __Infer<typeof BacktestResult>;

export const BrandKit = __t.object("BrandKit", {
  brandUserId: __t.string(),
  displayName: __t.string(),
  productDescription: __t.string(),
  valueProps: __t.array(__t.string()),
  palette: __t.array(__t.string()),
  visualStyle: __t.string(),
  bannedClaims: __t.array(__t.string()),
  referenceImageUrls: __t.array(__t.string()),
  updatedAt: __t.timestamp(),
});
export type BrandKit = __Infer<typeof BrandKit>;

export const BriefTheme = __t.object("BriefTheme", {
  text: __t.string(),
  support: __t.f64(),
  twinIds: __t.array(__t.string()),
});
export type BriefTheme = __Infer<typeof BriefTheme>;

export const Campaign = __t.object("Campaign", {
  campaignId: __t.string(),
  brandUserId: __t.string(),
  name: __t.string(),
  goal: __t.string(),
  offer: __t.option(__t.string()),
  channel: __t.string(),
  aspectRatio: __t.string(),
  segments: __t.array(__t.string()),
  variantsPerBrief: __t.u8(),
  status: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Campaign = __Infer<typeof Campaign>;

export const CascadeReplay = __t.object("CascadeReplay", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  runId: __t.string(),
});
export type CascadeReplay = __Infer<typeof CascadeReplay>;

export const CommentInput = __t.object("CommentInput", {
  userId: __t.string(),
  kind: __t.string(),
  text: __t.string(),
  tick: __t.u32(),
});
export type CommentInput = __Infer<typeof CommentInput>;

export const CreativeBrief = __t.object("CreativeBrief", {
  briefId: __t.string(),
  campaignId: __t.string(),
  segment: __t.string(),
  version: __t.u32(),
  audienceLabel: __t.string(),
  share: __t.f64(),
  twinCount: __t.u32(),
  get keyInterests() {
    return __t.array(BriefTheme);
  },
  get avoid() {
    return __t.array(BriefTheme);
  },
  tone: __t.string(),
  messageAngle: __t.string(),
  valueProps: __t.array(__t.string()),
  headlineOptions: __t.array(__t.string()),
  cta: __t.string(),
  visualCues: __t.array(__t.string()),
  visualAvoid: __t.array(__t.string()),
  format: __t.string(),
  model: __t.string(),
  evidenceJson: __t.option(__t.string()),
  editedByUser: __t.bool(),
  createdAt: __t.timestamp(),
});
export type CreativeBrief = __Infer<typeof CreativeBrief>;

export const CreativeJob = __t.object("CreativeJob", {
  jobId: __t.u64(),
  campaignId: __t.string(),
  kind: __t.string(),
  targetId: __t.string(),
  instruction: __t.option(__t.string()),
  aspectRatio: __t.option(__t.string()),
  status: __t.string(),
  requestedBy: __t.identity(),
  error: __t.option(__t.string()),
  reservedVariants: __t.u8(),
  claimedBy: __t.option(__t.identity()),
  claimedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  finishedAt: __t.option(__t.timestamp()),
});
export type CreativeJob = __Infer<typeof CreativeJob>;

export const EdgeInput = __t.object("EdgeInput", {
  a: __t.string(),
  b: __t.string(),
  kind: __t.string(),
});
export type EdgeInput = __Infer<typeof EdgeInput>;

export const LabExperiment = __t.object("LabExperiment", {
  experimentId: __t.u64(),
  brandUserId: __t.string(),
  brand: __t.string(),
  title: __t.string(),
  draftA: __t.string(),
  draftB: __t.string(),
  status: __t.string(),
  runA: __t.string(),
  runB: __t.string(),
  winner: __t.string(),
  lift: __t.f64(),
  error: __t.option(__t.string()),
  requestedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type LabExperiment = __Infer<typeof LabExperiment>;

export const Niche = __t.object("Niche", {
  slug: __t.string(),
  label: __t.string(),
  description: __t.string(),
});
export type Niche = __Infer<typeof Niche>;

export const SignalProbInput = __t.object("SignalProbInput", {
  userId: __t.string(),
  pLike: __t.f64(),
  pRepost: __t.f64(),
  pReply: __t.f64(),
  pQuote: __t.f64(),
});
export type SignalProbInput = __Infer<typeof SignalProbInput>;

export const SimCalibration = __t.object("SimCalibration", {
  scope: __t.string(),
  feedReach: __t.f64(),
  shareReach: __t.f64(),
  likeScale: __t.f64(),
  repostScale: __t.f64(),
  replyScale: __t.f64(),
  quoteScale: __t.f64(),
  source: __t.string(),
  note: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SimCalibration = __Infer<typeof SimCalibration>;

export const SimComment = __t.object("SimComment", {
  simCommentId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  kind: __t.string(),
  text: __t.string(),
  tick: __t.u32(),
});
export type SimComment = __Infer<typeof SimComment>;

export const SimEvent = __t.object("SimEvent", {
  simEventId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  signal: __t.string(),
  tick: __t.u32(),
});
export type SimEvent = __Infer<typeof SimEvent>;

export const SimNode = __t.object("SimNode", {
  simNodeId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  engagedShare: __t.f64(),
  seenShare: __t.f64(),
  replaySeenTick: __t.option(__t.u32()),
  replayEngagedTick: __t.option(__t.u32()),
});
export type SimNode = __Infer<typeof SimNode>;

export const SimNodeSignal = __t.object("SimNodeSignal", {
  simNodeSignalId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  likeShare: __t.f64(),
  repostShare: __t.f64(),
  replyShare: __t.f64(),
  quoteShare: __t.f64(),
});
export type SimNodeSignal = __Infer<typeof SimNodeSignal>;

export const SimOutsideTick = __t.object("SimOutsideTick", {
  simOutsideTickId: __t.string(),
  runId: __t.string(),
  tick: __t.u32(),
  views: __t.u32(),
  likes: __t.u32(),
  reposts: __t.u32(),
  replies: __t.u32(),
  quotes: __t.u32(),
});
export type SimOutsideTick = __Infer<typeof SimOutsideTick>;

export const SimProb = __t.object("SimProb", {
  simProbId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  pEngage: __t.f64(),
  action: __t.string(),
  reason: __t.string(),
});
export type SimProb = __Infer<typeof SimProb>;

export const SimProbInput = __t.object("SimProbInput", {
  userId: __t.string(),
  pEngage: __t.f64(),
  action: __t.string(),
  reason: __t.string(),
});
export type SimProbInput = __Infer<typeof SimProbInput>;

export const SimRun = __t.object("SimRun", {
  runId: __t.string(),
  brandUserId: __t.string(),
  draft: __t.string(),
  status: __t.string(),
  people: __t.u32(),
  trials: __t.u32(),
  reachP10: __t.u32(),
  reachP50: __t.u32(),
  reachP90: __t.u32(),
  seenP50: __t.u32(),
  replayTick: __t.u32(),
  replayMaxTick: __t.u32(),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type SimRun = __Infer<typeof SimRun>;

export const SimSignal = __t.object("SimSignal", {
  simSignalId: __t.string(),
  runId: __t.string(),
  signal: __t.string(),
  p10: __t.u32(),
  p50: __t.u32(),
  p90: __t.u32(),
  mean: __t.f64(),
});
export type SimSignal = __Infer<typeof SimSignal>;

export const SimSignalProb = __t.object("SimSignalProb", {
  simSignalProbId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  pLike: __t.f64(),
  pRepost: __t.f64(),
  pReply: __t.f64(),
  pQuote: __t.f64(),
});
export type SimSignalProb = __Infer<typeof SimSignalProb>;

export const SimSignalSource = __t.object("SimSignalSource", {
  simSignalSourceId: __t.string(),
  runId: __t.string(),
  signal: __t.string(),
  source: __t.string(),
  mean: __t.f64(),
});
export type SimSignalSource = __Infer<typeof SimSignalSource>;

export const Twin = __t.object("Twin", {
  userId: __t.string(),
  username: __t.string(),
  brandUserId: __t.string(),
  postCount: __t.u32(),
  replyShare: __t.f64(),
  quoteShare: __t.f64(),
  mentionRate: __t.f64(),
  avgLikes: __t.f64(),
  avgImpressions: __t.f64(),
  engagementRate: __t.f64(),
  activeHoursUtc: __t.byteArray(),
  get topics() {
    return __t.array(TwinTopic);
  },
  tone: __t.string(),
  personaSummary: __t.string(),
  hotButtons: __t.array(__t.string()),
  ignores: __t.array(__t.string()),
  formatPrefs: __t.array(__t.string()),
  evidencePostIds: __t.array(__t.string()),
  model: __t.string(),
  buildRunId: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Twin = __Infer<typeof Twin>;

export const TwinAudience = __t.object("TwinAudience", {
  twinAudienceId: __t.string(),
  brandUserId: __t.string(),
  userId: __t.string(),
  lastBuildRunId: __t.string(),
  updatedAt: __t.timestamp(),
});
export type TwinAudience = __Infer<typeof TwinAudience>;

export const TwinBuildJob = __t.object("TwinBuildJob", {
  jobId: __t.string(),
  runId: __t.string(),
  userId: __t.string(),
  username: __t.string(),
  status: __t.string(),
  error: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type TwinBuildJob = __Infer<typeof TwinBuildJob>;

export const TwinBuildRun = __t.object("TwinBuildRun", {
  runId: __t.string(),
  brandUserId: __t.string(),
  status: __t.string(),
  requested: __t.u32(),
  ready: __t.u32(),
  failed: __t.u32(),
  skipped: __t.u32(),
  startedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type TwinBuildRun = __Infer<typeof TwinBuildRun>;

export const TwinNiche = __t.object("TwinNiche", {
  twinNicheId: __t.string(),
  userId: __t.string(),
  niche: __t.string(),
  affinity: __t.f64(),
});
export type TwinNiche = __Infer<typeof TwinNiche>;

export const TwinQuestion = __t.object("TwinQuestion", {
  questionId: __t.u64(),
  userId: __t.string(),
  draft: __t.string(),
  question: __t.string(),
  askedBy: __t.identity(),
  status: __t.string(),
  action: __t.option(__t.string()),
  confidence: __t.option(__t.f64()),
  answer: __t.option(__t.string()),
  citedPostIds: __t.array(__t.string()),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  answeredAt: __t.option(__t.timestamp()),
});
export type TwinQuestion = __Infer<typeof TwinQuestion>;

export const TwinTopic = __t.object("TwinTopic", {
  topic: __t.string(),
  affinity: __t.f64(),
});
export type TwinTopic = __Infer<typeof TwinTopic>;

export const XContextAnnotation = __t.object("XContextAnnotation", {
  annotationId: __t.string(),
  postId: __t.string(),
  domainId: __t.string(),
  domainName: __t.string(),
  entityIdFromX: __t.string(),
  entityName: __t.string(),
  entityDescription: __t.option(__t.string()),
});
export type XContextAnnotation = __Infer<typeof XContextAnnotation>;

export const XIngestionRun = __t.object("XIngestionRun", {
  ingestionRunId: __t.string(),
  targetUsername: __t.string(),
  targetUserId: __t.option(__t.string()),
  startedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  status: __t.string(),
  followersRequested: __t.u32(),
  followersDiscovered: __t.u32(),
  followersProfilesSaved: __t.u32(),
  followersSkippedProtected: __t.u32(),
  followersFailed: __t.u32(),
  postsSaved: __t.u32(),
  lastProcessedUserId: __t.option(__t.string()),
  errorSummary: __t.option(__t.string()),
});
export type XIngestionRun = __Infer<typeof XIngestionRun>;

export const XPost = __t.object("XPost", {
  postId: __t.string(),
  authorUserId: __t.string(),
  text: __t.string(),
  createdAt: __t.string(),
  lang: __t.option(__t.string()),
  inReplyToUserId: __t.option(__t.string()),
  isReply: __t.bool(),
  isQuote: __t.bool(),
  impressionCount: __t.option(__t.u64()),
  likeCount: __t.option(__t.u64()),
  replyCount: __t.option(__t.u64()),
  quoteCount: __t.option(__t.u64()),
  repostCount: __t.option(__t.u64()),
  bookmarkCount: __t.option(__t.u64()),
  ingestedAt: __t.timestamp(),
});
export type XPost = __Infer<typeof XPost>;

export const XPostEntity = __t.object("XPostEntity", {
  entityId: __t.string(),
  postId: __t.string(),
  entityType: __t.string(),
  value: __t.string(),
  startOffset: __t.u32(),
  endOffset: __t.u32(),
  mentionedUserId: __t.option(__t.string()),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
});
export type XPostEntity = __Infer<typeof XPostEntity>;

export const XPostMedia = __t.object("XPostMedia", {
  id: __t.string(),
  postId: __t.string(),
  mediaKey: __t.string(),
  type: __t.string(),
  url: __t.option(__t.string()),
  altText: __t.option(__t.string()),
  viewCount: __t.option(__t.u64()),
});
export type XPostMedia = __Infer<typeof XPostMedia>;

export const XPostReference = __t.object("XPostReference", {
  id: __t.string(),
  postId: __t.string(),
  referencedPostId: __t.string(),
  referenceType: __t.string(),
});
export type XPostReference = __Infer<typeof XPostReference>;

export const XUser = __t.object("XUser", {
  userId: __t.string(),
  username: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  location: __t.option(__t.string()),
  createdAt: __t.option(__t.string()),
  url: __t.option(__t.string()),
  profileImageUrl: __t.option(__t.string()),
  protected: __t.option(__t.bool()),
  verified: __t.option(__t.bool()),
  verifiedType: __t.option(__t.string()),
  followersCount: __t.option(__t.u64()),
  followingCount: __t.option(__t.u64()),
  listedCount: __t.option(__t.u64()),
  postCount: __t.option(__t.u64()),
  likeCount: __t.option(__t.u64()),
  mediaCount: __t.option(__t.u64()),
  ingestedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  profileImage: __t.option(__t.string()),
});
export type XUser = __Infer<typeof XUser>;

