// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  ingestionRunId: __t.string(),
  targetUserId: __t.option(__t.string()),
  followersRequested: __t.u32(),
  followersDiscovered: __t.u32(),
  followersProfilesSaved: __t.u32(),
  followersSkippedProtected: __t.u32(),
  followersFailed: __t.u32(),
  postsSaved: __t.u32(),
  lastProcessedUserId: __t.option(__t.string()),
  errorSummary: __t.option(__t.string()),
};
