// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  jobId: __t.u64(),
  variantId: __t.string(),
  campaignId: __t.string(),
  briefId: __t.string(),
  parentVariantId: __t.option(__t.string()),
  rootVariantId: __t.string(),
  depth: __t.u8(),
  operation: __t.string(),
  instruction: __t.option(__t.string()),
  imagePrompt: __t.string(),
  headline: __t.string(),
  cta: __t.string(),
  aspectRatio: __t.string(),
  model: __t.string(),
  quality: __t.string(),
  status: __t.string(),
  imageUrl: __t.option(__t.string()),
  xaiFileId: __t.option(__t.string()),
  costUsdTicks: __t.u64(),
  error: __t.option(__t.string()),
};
