// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  userId: __t.string(),
  username: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  location: __t.option(__t.string()),
  createdAt: __t.option(__t.string()),
  url: __t.option(__t.string()),
  profileImageUrl: __t.option(__t.string()),
  protected: __t.option(__t.bool()),
  verified: __t.option(__t.bool()),
  verifiedType: __t.option(__t.string()),
  followersCount: __t.option(__t.u64()),
  followingCount: __t.option(__t.u64()),
  listedCount: __t.option(__t.u64()),
  postCount: __t.option(__t.u64()),
  likeCount: __t.option(__t.u64()),
  mediaCount: __t.option(__t.u64()),
};
