// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  postId: __t.string(),
  authorUserId: __t.string(),
  text: __t.string(),
  createdAt: __t.string(),
  lang: __t.option(__t.string()),
  inReplyToUserId: __t.option(__t.string()),
  isReply: __t.bool(),
  isQuote: __t.bool(),
  impressionCount: __t.option(__t.u64()),
  likeCount: __t.option(__t.u64()),
  replyCount: __t.option(__t.u64()),
  quoteCount: __t.option(__t.u64()),
  repostCount: __t.option(__t.u64()),
  bookmarkCount: __t.option(__t.u64()),
};
