// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  videoId: __t.string().primaryKey().name("video_id"),
  likeMin: __t.u32().name("like_min"),
  likeMax: __t.u32().name("like_max"),
  repostMin: __t.u32().name("repost_min"),
  repostMax: __t.u32().name("repost_max"),
  updatedAt: __t.timestamp().name("updated_at"),
});
