// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  videoId: __t.string().primaryKey().name("video_id"),
  parentId: __t.string().name("parent_id"),
  instruction: __t.string(),
  beatsJson: __t.string().name("beats_json"),
  createdAt: __t.timestamp().name("created_at"),
});
