// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  annotationId: __t.string().primaryKey().name("annotation_id"),
  postId: __t.string().name("post_id"),
  domainId: __t.string().name("domain_id"),
  domainName: __t.string().name("domain_name"),
  entityIdFromX: __t.string().name("entity_id_from_x"),
  entityName: __t.string().name("entity_name"),
  entityDescription: __t.option(__t.string()).name("entity_description"),
});
