// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ingestionRunId: __t.string().primaryKey().name("ingestion_run_id"),
  targetUsername: __t.string().name("target_username"),
  targetUserId: __t.option(__t.string()).name("target_user_id"),
  startedAt: __t.timestamp().name("started_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  status: __t.string(),
  followersRequested: __t.u32().name("followers_requested"),
  followersDiscovered: __t.u32().name("followers_discovered"),
  followersProfilesSaved: __t.u32().name("followers_profiles_saved"),
  followersSkippedProtected: __t.u32().name("followers_skipped_protected"),
  followersFailed: __t.u32().name("followers_failed"),
  postsSaved: __t.u32().name("posts_saved"),
  lastProcessedUserId: __t.option(__t.string()).name("last_processed_user_id"),
  errorSummary: __t.option(__t.string()).name("error_summary"),
});
