// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  postId: __t.string().primaryKey().name("post_id"),
  authorUserId: __t.string().name("author_user_id"),
  text: __t.string(),
  createdAt: __t.string().name("created_at"),
  lang: __t.option(__t.string()),
  inReplyToUserId: __t.option(__t.string()).name("in_reply_to_user_id"),
  isReply: __t.bool().name("is_reply"),
  isQuote: __t.bool().name("is_quote"),
  impressionCount: __t.option(__t.u64()).name("impression_count"),
  likeCount: __t.option(__t.u64()).name("like_count"),
  replyCount: __t.option(__t.u64()).name("reply_count"),
  quoteCount: __t.option(__t.u64()).name("quote_count"),
  repostCount: __t.option(__t.u64()).name("repost_count"),
  bookmarkCount: __t.option(__t.u64()).name("bookmark_count"),
  ingestedAt: __t.timestamp().name("ingested_at"),
});
