// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  username: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  location: __t.option(__t.string()),
  createdAt: __t.option(__t.string()).name("created_at"),
  url: __t.option(__t.string()),
  profileImageUrl: __t.option(__t.string()).name("profile_image_url"),
  protected: __t.option(__t.bool()),
  verified: __t.option(__t.bool()),
  verifiedType: __t.option(__t.string()).name("verified_type"),
  followersCount: __t.option(__t.u64()).name("followers_count"),
  followingCount: __t.option(__t.u64()).name("following_count"),
  listedCount: __t.option(__t.u64()).name("listed_count"),
  postCount: __t.option(__t.u64()).name("post_count"),
  likeCount: __t.option(__t.u64()).name("like_count"),
  mediaCount: __t.option(__t.u64()).name("media_count"),
  ingestedAt: __t.timestamp().name("ingested_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  profileImage: __t.option(__t.string()).name("profile_image"),
});
