import { WorkspaceAccount } from './components/WorkspaceAccount';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Pause,Play,RotateCcw,Sun,Moon,Move,Network,Sparkles} from 'lucide-react';
import {RippleMark} from './App';
import {NetworkCanvas} from './visuals/NetworkCanvas';
import {communities,profiles,type Concept} from './visuals/network';
import './visuals.css';
const concepts:{id:Concept;name:string;label:string;description:string}[]=[
  {id:'constellation',name:'Human constellation',label:'01 / SPATIAL',description:'A living audience map. Portraits float in distinct communities, grouped by shared interests.'},
  {id:'orbit',name:'People, in orbit',label:'02 / SPHERICAL',description:'An audience you can turn in your hands. A globe of people, with depth, perspective, and clearly separated communities.'},
  {id:'bridge',name:'Community pockets',label:'03 / CLUSTERS',description:'Compact groups of people, with each community presented on its own.'},
];
export default function VisualsPage(){
  const [concept,setConcept]=useState<Concept>('constellation');
  const [playing,setPlaying]=useState(true),[theme,setTheme]=useState<'dark'|'light'>('dark'),[selected,setSelected]=useState(12),[replay,setReplay]=useState(0);
  const chosen=concepts.find(c=>c.id===concept)!,profile=profiles[selected];
  useEffect(()=>{document.documentElement.dataset.theme=theme;document.title='Ripple — Visual playground';},[theme]);
  return <div className="visuals-page"><header className="visuals-header"><a className="brand" href="/"><RippleMark size={26}/><span>Ripple</span></a><span className="visuals-kicker">VISUAL PLAYGROUND / 001</span><div><a href="/"><ArrowLeft size={14}/> Landing page</a><button aria-label={theme==='dark'?'Switch to light mode':'Switch to dark mode'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button></div><WorkspaceAccount /></header>
    <main className="visuals-main"><div className="visuals-intro"><div><span className="eyebrow"><Sparkles size={11}/> A FEW POSSIBLE FUTURES</span><h1>A network.<br/><span>With people in it.</span></h1></div><p>Less chart. More living constellation.<br/>Three directions for watching an idea find its people.</p></div>
      <div className="concept-tabs" role="tablist" aria-label="Network visual concepts">{concepts.map(c=><button key={c.id} role="tab" id={`tab-${c.id}`} aria-controls="network-panel" aria-selected={concept===c.id} className={concept===c.id?'active':''} onClick={()=>setConcept(c.id)}><span>{c.label}</span>{c.name}<ArrowUpRight size={15}/></button>)}</div>
      <section className="visuals-stage" id="network-panel" role="tabpanel" aria-labelledby={`tab-${concept}`}><div className="scene-toolbar"><span><i/> {chosen.name}</span><div><button aria-label={playing?'Pause animation':'Play animation'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={13}/>:<Play size={13}/>}<span>{playing?'Pause':'Play'}</span></button><button aria-label="Replay cascade" onClick={()=>{setReplay(v=>v+1);setPlaying(true);}}><RotateCcw size={13}/><span>Replay</span></button></div></div>
        <div className="scene-body"><div className="scene-canvas"><NetworkCanvas concept={concept} playing={playing} theme={theme} selected={selected} onSelect={setSelected} replay={replay}/><div className="scene-instructions"><Move size={12}/> Drag to orbit · Scroll to zoom · Tap a person</div><div className="scene-scale"><i/><span>48 sample profiles · 4 communities</span></div></div><aside className="profile-inspector"><span className="eyebrow">A PERSON, NOT A DOT</span><div className="inspector-avatar" style={{borderColor:communities[profile.community].color}}><img key={profile.avatar} src={profile.avatar} alt={`Demo portrait for ${profile.name}`} onError={e=>{e.currentTarget.style.display='none';}}/><span>{profile.initials}</span></div><h2>{profile.name}</h2><span className="profile-community"><i style={{background:communities[profile.community].color}}/>{communities[profile.community].name}</span><div className="profile-note"><Network size={16}/><strong>{profile.role}</strong><p>A member of the sample audience. Explore people within each community.</p></div><div className="inspector-facts"><span>Visual language <b>Portraits + depth</b></span><span>Motion <b>Orbit + cascade</b></span><span>Data <b>Illustrative</b></span></div><label className="profile-select-label" htmlFor="profile-selector">Explore a profile</label><select id="profile-selector" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {communities[p.community].name}</option>)}</select></aside></div><div className="scene-legend">{communities.map(c=><span key={c.name}><i style={{background:c.color}}/>{c.name}</span>)}</div></section>
      <div className="concept-explanation"><div><span className="eyebrow">THE IDEA</span><h2>{chosen.name}</h2><p>{chosen.description}</p></div><div className="visuals-next"><span className="eyebrow">WHEN CONNECTED</span><p>Real profile avatars. Your audience graph.<br/>A cascade you can follow, person by person.</p><small>This is a visual prototype, using demo portraits from Pravatar. No real audience data or predictions.</small></div></div>
    </main><footer className="visuals-footer"><span>Ripple / Motion studies</span><span>Choose a direction. We’ll take it further.</span></footer></div>;
}
